# Generated by Django 4.2.4 on 2024-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
