# Generated by Django 4.2.4 on 2024-06-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_useraccounts_user_alter_company_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserAccounts",
        ),
    ]
