# Generated by Django 4.2.4 on 2024-06-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_useraccounts_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccounts",
            name="password",
        ),
    ]
