# Generated by Django 4.2.4 on 2024-06-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_useraccounts_groups_useraccounts_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccounts",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="useraccounts",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="useraccounts",
            name="user_permissions",
        ),
    ]
